### NumPy
Check the [User's Guide](https://docs.scipy.org/doc/numpy/user/index.html)

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

In [1]:
import numpy as np

##### Setting numpy array variables

In [31]:
a = [1,2,3,4]
print(type(a))
npa = np.array(a)
print(type(npa))
print(npa.dtype)
print(npa.size)
print(npa.shape)

<class 'list'>
<class 'numpy.ndarray'>
int64
4
(4,)


In [22]:
b = [1.,2.,3.,4.]
print(type(b))
npb = np.array(b)
print(type(npb))
print(npb.dtype)

<class 'list'>
<class 'numpy.ndarray'>
float64


In [16]:
c = [1,2,3,4]
print(type(c))
npc = np.array(c,dtype="float32")
print(type(npc))
print(npc.dtype)

<class 'list'>
<class 'numpy.ndarray'>
float32


In [33]:
c = [5,6,7,8]
print(type(c))
npc = np.array([c],dtype="float32")
print(type(npc))
print(npc.dtype)
print(npc.size)
print(npc.shape)

<class 'list'>
<class 'numpy.ndarray'>
float32
4
(1, 4)


##### Initializing numpy array variables

In [34]:
zr = np.zeros( (3,4) )
print(zr.dtype)
print(zr.shape)
print(zr.size)
print(zr)

float64
(3, 4)
12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
on = np.ones( (2,3,4) , dtype=np.int32)
print(on.dtype)
print(on.shape)
print(on.size)
print(on)

int32
(2, 3, 4)
24
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [37]:
em = np.empty( (2,3) , dtype="int32")
print(em.dtype)
print(em)

int32
[[21917712    22037      101]
 [      41       48        0]]


##### Concatenation

In [67]:
for i in range(len(em)):
    em[i] = i*3
print(em)
print(em[1][0])
print(em[0][1])

[[0 0 0]
 [3 3 3]]
3
0


In [68]:
new = np.array([[6,6,6]])
print(new.shape)
print(em.shape)
concat = np.concatenate((em,new))
print(concat)

(1, 3)
(2, 3)
[[0 0 0]
 [3 3 3]
 [6 6 6]]


##### Vector and Matrix operations

In [74]:
concat += 2.5
print(concat)

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [70]:
concat += 2
print(concat)

[[2 2 2]
 [5 5 5]
 [8 8 8]]


In [75]:
addendum = np.array([1,2,3])
result = concat + addendum
print(result)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [91]:
factor = np.array([1,2,3])
result = concat * factor
print(result)
result = concat / factor
print(result)

[[ 2  4  6]
 [ 5 10 15]
 [ 8 16 24]]
[[2.         1.         0.66666667]
 [5.         2.5        1.66666667]
 [8.         4.         2.66666667]]


In [80]:
factor = np.array([[1,2,3],[4,5,6],[3,2,1]])
result = concat * factor
print(result)
result = em * factor
print(result)

[[ 2  4  6]
 [20 25 30]
 [24 16  8]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [79]:
result = concat @ factor
print(result)
result = em @ factor
print(result)

[[16 18 20]
 [40 45 50]
 [64 72 80]]
[[ 0  0  0]
 [24 27 30]]


In [83]:
nozr = em > 0 
pos = np.nonzero(em)
print(nozr)
print(type(nozr))
print(pos)
print(type(pos))

[[False False False]
 [ True  True  True]]
<class 'numpy.ndarray'>
(array([1, 1, 1]), array([0, 1, 2]))
<class 'tuple'>


In [85]:
sum(result)

array([46, 45, 44])

In [86]:
np.mean(result)

15.0

In [87]:
np.cov(result)

array([[  4.,  10., -16.],
       [ 10.,  25., -40.],
       [-16., -40.,  64.]])